// Generated by gencpp from file flow_publisher/FlowDataMsg.msg
// DO NOT EDIT!


#ifndef FLOW_PUBLISHER_MESSAGE_FLOWDATAMSG_H
#define FLOW_PUBLISHER_MESSAGE_FLOWDATAMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flow_publisher
{
template <class ContainerAllocator>
struct FlowDataMsg_
{
  typedef FlowDataMsg_<ContainerAllocator> Type;

  FlowDataMsg_()
    : flow_x_integral(0)
    , flow_y_integral(0)
    , ground_distance(0.0)  {
    }
  FlowDataMsg_(const ContainerAllocator& _alloc)
    : flow_x_integral(0)
    , flow_y_integral(0)
    , ground_distance(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _flow_x_integral_type;
  _flow_x_integral_type flow_x_integral;

   typedef int16_t _flow_y_integral_type;
  _flow_y_integral_type flow_y_integral;

   typedef float _ground_distance_type;
  _ground_distance_type ground_distance;





  typedef boost::shared_ptr< ::flow_publisher::FlowDataMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flow_publisher::FlowDataMsg_<ContainerAllocator> const> ConstPtr;

}; // struct FlowDataMsg_

typedef ::flow_publisher::FlowDataMsg_<std::allocator<void> > FlowDataMsg;

typedef boost::shared_ptr< ::flow_publisher::FlowDataMsg > FlowDataMsgPtr;
typedef boost::shared_ptr< ::flow_publisher::FlowDataMsg const> FlowDataMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flow_publisher::FlowDataMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flow_publisher::FlowDataMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flow_publisher::FlowDataMsg_<ContainerAllocator1> & lhs, const ::flow_publisher::FlowDataMsg_<ContainerAllocator2> & rhs)
{
  return lhs.flow_x_integral == rhs.flow_x_integral &&
    lhs.flow_y_integral == rhs.flow_y_integral &&
    lhs.ground_distance == rhs.ground_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flow_publisher::FlowDataMsg_<ContainerAllocator1> & lhs, const ::flow_publisher::FlowDataMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flow_publisher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flow_publisher::FlowDataMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flow_publisher::FlowDataMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flow_publisher::FlowDataMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flow_publisher::FlowDataMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flow_publisher::FlowDataMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flow_publisher::FlowDataMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flow_publisher::FlowDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66f15ac7ac0281db583d79d134e42e32";
  }

  static const char* value(const ::flow_publisher::FlowDataMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66f15ac7ac0281dbULL;
  static const uint64_t static_value2 = 0x583d79d134e42e32ULL;
};

template<class ContainerAllocator>
struct DataType< ::flow_publisher::FlowDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flow_publisher/FlowDataMsg";
  }

  static const char* value(const ::flow_publisher::FlowDataMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flow_publisher::FlowDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 flow_x_integral\n"
"int16 flow_y_integral\n"
"float32 ground_distance\n"
;
  }

  static const char* value(const ::flow_publisher::FlowDataMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flow_publisher::FlowDataMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flow_x_integral);
      stream.next(m.flow_y_integral);
      stream.next(m.ground_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlowDataMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flow_publisher::FlowDataMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flow_publisher::FlowDataMsg_<ContainerAllocator>& v)
  {
    s << indent << "flow_x_integral: ";
    Printer<int16_t>::stream(s, indent + "  ", v.flow_x_integral);
    s << indent << "flow_y_integral: ";
    Printer<int16_t>::stream(s, indent + "  ", v.flow_y_integral);
    s << indent << "ground_distance: ";
    Printer<float>::stream(s, indent + "  ", v.ground_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLOW_PUBLISHER_MESSAGE_FLOWDATAMSG_H
