/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_simple_drag_delay_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {-2.9180000000000000e-01, -3.1530000000000002e-01, -1.6700000000000000e-02};
static const casadi_real casadi_c2[3] = {0., 0., 9.8000000000000007e+00};

/* drone_simple_drag_delay_expl_ode_fun:(i0[17],i1[4],i2[0])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, *w02=w+4, w03, *w04=w+9, *w05=w+12, *w06=w+15, w07, *w08=w+20, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, *w17=w+31, *w18=w+34, *w19=w+37, w20, w21, w22;
  casadi_real *w23=w+43, w24;
  const casadi_real *cr, *cs;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w00);
  /* #1: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  /* #2: @1 = input[0][4] */
  w01 = arg[0] ? arg[0][13] : 0;
  /* #3: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w02);
  /* #4: @3 = @2[0] */
  for (rr=(&w03), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #5: @4 = @2[1:4] */
  for (rr=w04, cs=w02+1; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #6: @5 = (-@4) */
  for (i=0, rr=w05, cs=w04; i<3; ++i) *rr++ = (- *cs++ );
  /* #7: @6 = vertcat(@3, @5) */
  rr=w06;
  *rr++ = w03;
  for (i=0, cs=w05; i<3; ++i) *rr++ = *cs++;
  /* #8: @7 = ||@2||_F */
  w07 = casadi_norm_2(4, w02);
  /* #9: @7 = sq(@7) */
  w07 = casadi_sq( w07 );
  /* #10: @6 = (@6/@7) */
  for (i=0, rr=w06; i<4; ++i) (*rr++) /= w07;
  /* #11: @7 = @6[0] */
  for (rr=(&w07), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #12: @5 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w05);
  /* #13: @8 = (@5*@3) */
  for (i=0, rr=w08, cr=w05; i<3; ++i) (*rr++)  = ((*cr++)*w03);
  /* #14: @9 = @2[2] */
  for (rr=(&w09), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #15: @10 = @5[2] */
  for (rr=(&w10), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #16: @11 = (@9*@10) */
  w11  = (w09*w10);
  /* #17: @12 = @2[3] */
  for (rr=(&w12), cs=w02+3; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #18: @13 = @5[1] */
  for (rr=(&w13), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #19: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #20: @11 = (@11-@14) */
  w11 -= w14;
  /* #21: @14 = @5[0] */
  for (rr=(&w14), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #22: @15 = (@12*@14) */
  w15  = (w12*w14);
  /* #23: @16 = @2[1] */
  for (rr=(&w16), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #24: @10 = (@16*@10) */
  w10  = (w16*w10);
  /* #25: @15 = (@15-@10) */
  w15 -= w10;
  /* #26: @13 = (@16*@13) */
  w13  = (w16*w13);
  /* #27: @14 = (@9*@14) */
  w14  = (w09*w14);
  /* #28: @13 = (@13-@14) */
  w13 -= w14;
  /* #29: @17 = vertcat(@11, @15, @13) */
  rr=w17;
  *rr++ = w11;
  *rr++ = w15;
  *rr++ = w13;
  /* #30: @8 = (@8+@17) */
  for (i=0, rr=w08, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #31: @17 = (@7*@8) */
  for (i=0, rr=w17, cs=w08; i<3; ++i) (*rr++)  = (w07*(*cs++));
  /* #32: @11 = dot(@4, @5) */
  w11 = casadi_dot(3, w04, w05);
  /* #33: @18 = @6[1:4] */
  for (rr=w18, cs=w06+1; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #34: @19 = (@11*@18) */
  for (i=0, rr=w19, cs=w18; i<3; ++i) (*rr++)  = (w11*(*cs++));
  /* #35: @17 = (@17-@19) */
  for (i=0, rr=w17, cs=w19; i<3; ++i) (*rr++) -= (*cs++);
  /* #36: @11 = @8[1] */
  for (rr=(&w11), cs=w08+1; cs!=w08+2; cs+=1) *rr++ = *cs;
  /* #37: @15 = @6[3] */
  for (rr=(&w15), cs=w06+3; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #38: @13 = (@11*@15) */
  w13  = (w11*w15);
  /* #39: @14 = @8[2] */
  for (rr=(&w14), cs=w08+2; cs!=w08+3; cs+=1) *rr++ = *cs;
  /* #40: @10 = @6[2] */
  for (rr=(&w10), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #41: @20 = (@14*@10) */
  w20  = (w14*w10);
  /* #42: @13 = (@13-@20) */
  w13 -= w20;
  /* #43: @20 = @6[1] */
  for (rr=(&w20), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #44: @14 = (@14*@20) */
  w14 *= w20;
  /* #45: @21 = @8[0] */
  for (rr=(&w21), cs=w08+0; cs!=w08+1; cs+=1) *rr++ = *cs;
  /* #46: @22 = (@21*@15) */
  w22  = (w21*w15);
  /* #47: @14 = (@14-@22) */
  w14 -= w22;
  /* #48: @21 = (@21*@10) */
  w21 *= w10;
  /* #49: @11 = (@11*@20) */
  w11 *= w20;
  /* #50: @21 = (@21-@11) */
  w21 -= w11;
  /* #51: @8 = vertcat(@13, @14, @21) */
  rr=w08;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w21;
  /* #52: @17 = (@17+@8) */
  for (i=0, rr=w17, cs=w08; i<3; ++i) (*rr++) += (*cs++);
  /* #53: @17 = (@1*@17) */
  for (i=0, rr=w17, cs=w17; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #54: @8 = [-0.2918, -0.3153, -0.0167] */
  casadi_copy(casadi_c1, 3, w08);
  /* #55: @19 = (-@18) */
  for (i=0, rr=w19, cs=w18; i<3; ++i) *rr++ = (- *cs++ );
  /* #56: @2 = vertcat(@7, @19) */
  rr=w02;
  *rr++ = w07;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  /* #57: @1 = ||@6||_F */
  w01 = casadi_norm_2(4, w06);
  /* #58: @1 = sq(@1) */
  w01 = casadi_sq( w01 );
  /* #59: @2 = (@2/@1) */
  for (i=0, rr=w02; i<4; ++i) (*rr++) /= w01;
  /* #60: @1 = @2[0] */
  for (rr=(&w01), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #61: @19 = (@7*@0) */
  for (i=0, rr=w19, cs=w00; i<3; ++i) (*rr++)  = (w07*(*cs++));
  /* #62: @13 = @0[2] */
  for (rr=(&w13), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #63: @14 = (@10*@13) */
  w14  = (w10*w13);
  /* #64: @21 = @0[1] */
  for (rr=(&w21), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #65: @11 = (@15*@21) */
  w11  = (w15*w21);
  /* #66: @14 = (@14-@11) */
  w14 -= w11;
  /* #67: @11 = @0[0] */
  for (rr=(&w11), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #68: @22 = (@15*@11) */
  w22  = (w15*w11);
  /* #69: @13 = (@20*@13) */
  w13  = (w20*w13);
  /* #70: @22 = (@22-@13) */
  w22 -= w13;
  /* #71: @21 = (@20*@21) */
  w21  = (w20*w21);
  /* #72: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #73: @21 = (@21-@11) */
  w21 -= w11;
  /* #74: @23 = vertcat(@14, @22, @21) */
  rr=w23;
  *rr++ = w14;
  *rr++ = w22;
  *rr++ = w21;
  /* #75: @19 = (@19+@23) */
  for (i=0, rr=w19, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #76: @23 = (@1*@19) */
  for (i=0, rr=w23, cs=w19; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #77: @1 = dot(@18, @0) */
  w01 = casadi_dot(3, w18, w00);
  /* #78: @0 = @2[1:4] */
  for (rr=w00, cs=w02+1; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #79: @0 = (@1*@0) */
  for (i=0, rr=w00, cs=w00; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #80: @23 = (@23-@0) */
  for (i=0, rr=w23, cs=w00; i<3; ++i) (*rr++) -= (*cs++);
  /* #81: @1 = @19[1] */
  for (rr=(&w01), cs=w19+1; cs!=w19+2; cs+=1) *rr++ = *cs;
  /* #82: @14 = @2[3] */
  for (rr=(&w14), cs=w02+3; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #83: @22 = (@1*@14) */
  w22  = (w01*w14);
  /* #84: @21 = @19[2] */
  for (rr=(&w21), cs=w19+2; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #85: @11 = @2[2] */
  for (rr=(&w11), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #86: @13 = (@21*@11) */
  w13  = (w21*w11);
  /* #87: @22 = (@22-@13) */
  w22 -= w13;
  /* #88: @13 = @2[1] */
  for (rr=(&w13), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #89: @21 = (@21*@13) */
  w21 *= w13;
  /* #90: @24 = @19[0] */
  for (rr=(&w24), cs=w19+0; cs!=w19+1; cs+=1) *rr++ = *cs;
  /* #91: @14 = (@24*@14) */
  w14  = (w24*w14);
  /* #92: @21 = (@21-@14) */
  w21 -= w14;
  /* #93: @24 = (@24*@11) */
  w24 *= w11;
  /* #94: @1 = (@1*@13) */
  w01 *= w13;
  /* #95: @24 = (@24-@1) */
  w24 -= w01;
  /* #96: @19 = vertcat(@22, @21, @24) */
  rr=w19;
  *rr++ = w22;
  *rr++ = w21;
  *rr++ = w24;
  /* #97: @23 = (@23+@19) */
  for (i=0, rr=w23, cs=w19; i<3; ++i) (*rr++) += (*cs++);
  /* #98: @8 = (@8*@23) */
  for (i=0, rr=w08, cs=w23; i<3; ++i) (*rr++) *= (*cs++);
  /* #99: @22 = 0.005 */
  w22 = 5.0000000000000001e-03;
  /* #100: @21 = @23[0] */
  for (rr=(&w21), cs=w23+0; cs!=w23+1; cs+=1) *rr++ = *cs;
  /* #101: @21 = sq(@21) */
  w21 = casadi_sq( w21 );
  /* #102: @24 = @23[1] */
  for (rr=(&w24), cs=w23+1; cs!=w23+2; cs+=1) *rr++ = *cs;
  /* #103: @24 = sq(@24) */
  w24 = casadi_sq( w24 );
  /* #104: @21 = (@21+@24) */
  w21 += w24;
  /* #105: @22 = (@22*@21) */
  w22 *= w21;
  /* #106: @21 = -0.0949 */
  w21 = -9.4899999999999998e-02;
  /* #107: @24 = @23[2] */
  for (rr=(&w24), cs=w23+2; cs!=w23+3; cs+=1) *rr++ = *cs;
  /* #108: @21 = (@21*@24) */
  w21 *= w24;
  /* #109: @21 = (@21*@24) */
  w21 *= w24;
  /* #110: @22 = (@22+@21) */
  w22 += w21;
  /* #111: @5 = (@5*@22) */
  for (i=0, rr=w05; i<3; ++i) (*rr++) *= w22;
  /* #112: @8 = (@8+@5) */
  for (i=0, rr=w08, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #113: @5 = (@3*@8) */
  for (i=0, rr=w05, cs=w08; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #114: @22 = @8[2] */
  for (rr=(&w22), cs=w08+2; cs!=w08+3; cs+=1) *rr++ = *cs;
  /* #115: @21 = (@9*@22) */
  w21  = (w09*w22);
  /* #116: @24 = @8[1] */
  for (rr=(&w24), cs=w08+1; cs!=w08+2; cs+=1) *rr++ = *cs;
  /* #117: @1 = (@12*@24) */
  w01  = (w12*w24);
  /* #118: @21 = (@21-@1) */
  w21 -= w01;
  /* #119: @1 = @8[0] */
  for (rr=(&w01), cs=w08+0; cs!=w08+1; cs+=1) *rr++ = *cs;
  /* #120: @13 = (@12*@1) */
  w13  = (w12*w01);
  /* #121: @22 = (@16*@22) */
  w22  = (w16*w22);
  /* #122: @13 = (@13-@22) */
  w13 -= w22;
  /* #123: @24 = (@16*@24) */
  w24  = (w16*w24);
  /* #124: @1 = (@9*@1) */
  w01  = (w09*w01);
  /* #125: @24 = (@24-@1) */
  w24 -= w01;
  /* #126: @23 = vertcat(@21, @13, @24) */
  rr=w23;
  *rr++ = w21;
  *rr++ = w13;
  *rr++ = w24;
  /* #127: @5 = (@5+@23) */
  for (i=0, rr=w05, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #128: @23 = (@7*@5) */
  for (i=0, rr=w23, cs=w05; i<3; ++i) (*rr++)  = (w07*(*cs++));
  /* #129: @7 = dot(@4, @8) */
  w07 = casadi_dot(3, w04, w08);
  /* #130: @18 = (@7*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w07*(*cs++));
  /* #131: @23 = (@23-@18) */
  for (i=0, rr=w23, cs=w18; i<3; ++i) (*rr++) -= (*cs++);
  /* #132: @7 = @5[1] */
  for (rr=(&w07), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #133: @21 = (@7*@15) */
  w21  = (w07*w15);
  /* #134: @13 = @5[2] */
  for (rr=(&w13), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #135: @24 = (@13*@10) */
  w24  = (w13*w10);
  /* #136: @21 = (@21-@24) */
  w21 -= w24;
  /* #137: @13 = (@13*@20) */
  w13 *= w20;
  /* #138: @24 = @5[0] */
  for (rr=(&w24), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #139: @15 = (@24*@15) */
  w15  = (w24*w15);
  /* #140: @13 = (@13-@15) */
  w13 -= w15;
  /* #141: @24 = (@24*@10) */
  w24 *= w10;
  /* #142: @7 = (@7*@20) */
  w07 *= w20;
  /* #143: @24 = (@24-@7) */
  w24 -= w07;
  /* #144: @5 = vertcat(@21, @13, @24) */
  rr=w05;
  *rr++ = w21;
  *rr++ = w13;
  *rr++ = w24;
  /* #145: @23 = (@23+@5) */
  for (i=0, rr=w23, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #146: @17 = (@17+@23) */
  for (i=0, rr=w17, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #147: @23 = [0, 0, 9.8] */
  casadi_copy(casadi_c2, 3, w23);
  /* #148: @17 = (@17-@23) */
  for (i=0, rr=w17, cs=w23; i<3; ++i) (*rr++) -= (*cs++);
  /* #149: output[0][1] = @17 */
  if (res[0]) casadi_copy(w17, 3, res[0]+3);
  /* #150: @21 = 0.5 */
  w21 = 5.0000000000000000e-01;
  /* #151: @17 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w17);
  /* #152: @13 = dot(@4, @17) */
  w13 = casadi_dot(3, w04, w17);
  /* #153: @13 = (-@13) */
  w13 = (- w13 );
  /* #154: @4 = (@3*@17) */
  for (i=0, rr=w04, cs=w17; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #155: @3 = @17[2] */
  for (rr=(&w03), cs=w17+2; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #156: @24 = (@9*@3) */
  w24  = (w09*w03);
  /* #157: @7 = @17[1] */
  for (rr=(&w07), cs=w17+1; cs!=w17+2; cs+=1) *rr++ = *cs;
  /* #158: @20 = (@12*@7) */
  w20  = (w12*w07);
  /* #159: @24 = (@24-@20) */
  w24 -= w20;
  /* #160: @20 = @17[0] */
  for (rr=(&w20), cs=w17+0; cs!=w17+1; cs+=1) *rr++ = *cs;
  /* #161: @12 = (@12*@20) */
  w12 *= w20;
  /* #162: @3 = (@16*@3) */
  w03  = (w16*w03);
  /* #163: @12 = (@12-@3) */
  w12 -= w03;
  /* #164: @16 = (@16*@7) */
  w16 *= w07;
  /* #165: @9 = (@9*@20) */
  w09 *= w20;
  /* #166: @16 = (@16-@9) */
  w16 -= w09;
  /* #167: @23 = vertcat(@24, @12, @16) */
  rr=w23;
  *rr++ = w24;
  *rr++ = w12;
  *rr++ = w16;
  /* #168: @4 = (@4+@23) */
  for (i=0, rr=w04, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #169: @2 = vertcat(@13, @4) */
  rr=w02;
  *rr++ = w13;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  /* #170: @2 = (@21*@2) */
  for (i=0, rr=w02, cs=w02; i<4; ++i) (*rr++)  = (w21*(*cs++));
  /* #171: output[0][2] = @2 */
  if (res[0]) casadi_copy(w02, 4, res[0]+6);
  /* #172: @21 = 20 */
  w21 = 20.;
  /* #173: @4 = input[0][5] */
  casadi_copy(arg[0] ? arg[0]+14 : 0, 3, w04);
  /* #174: @4 = (@4-@17) */
  for (i=0, rr=w04, cs=w17; i<3; ++i) (*rr++) -= (*cs++);
  /* #175: @4 = (@21*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #176: output[0][3] = @4 */
  if (res[0]) casadi_copy(w04, 3, res[0]+10);
  /* #177: @21 = input[1][0] */
  w21 = arg[1] ? arg[1][0] : 0;
  /* #178: output[0][4] = @21 */
  if (res[0]) res[0][13] = w21;
  /* #179: @4 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w04);
  /* #180: output[0][5] = @4 */
  if (res[0]) casadi_copy(w04, 3, res[0]+14);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_delay_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_delay_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_delay_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_delay_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_delay_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_delay_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_delay_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_delay_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_delay_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_delay_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real drone_simple_drag_delay_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_delay_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_delay_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_delay_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_delay_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_delay_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 47;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_delay_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 47*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
