/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_simple_drag_delay_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[22] = 
  {21, 1, 0, 18, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15, 16, 17, 18, 19, 20};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {-2.9180000000000000e-01, -3.1530000000000002e-01, -1.6700000000000000e-02};

static const casadi_real casadi_zeros[17] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* drone_simple_drag_delay_expl_vde_adj:(i0[17],i1[17],i2[4],i3[0])->(o0[21x1,18nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, *w02=w+5, *w03=w+8, *w04=w+11, w05, w06, w07, *w08=w+18, *w09=w+21, w10;
  casadi_real w11, *w12=w+27, w13, w14, *w15=w+32, *w16=w+35, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, *w27=w+48, *w28=w+51, w29, w30, w31, w32, w33, w34;
  casadi_real w35, *w37=w+78, *w39=w+84, *w40=w+88, *w42=w+94, w43, w44, w45, w46, w47, w48, *w49=w+103;
  casadi_real *w50=w+106, w51, w52, w53, w54, w55, w56, w57, *w58=w+116, w59, w60, w61;
  casadi_real w62, *w63=w+123, *w64=w+126, w65, w66, w67, w68, w69, *w70=w+135, *w71=w+139, *w72=w+143;
  const casadi_real *cr, *cs, *wr36, *wr37, *wr38, *wr39, *wr40, *wr41;
  /* #0: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w00);
  /* #1: @1 = @0[0] */
  for (rr=(&w01), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #2: @2 = @0[1:4] */
  for (rr=w02, cs=w00+1; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #3: @3 = (-@2) */
  for (i=0, rr=w03, cs=w02; i<3; ++i) *rr++ = (- *cs++ );
  /* #4: @4 = vertcat(@1, @3) */
  rr=w04;
  *rr++ = w01;
  for (i=0, cs=w03; i<3; ++i) *rr++ = *cs++;
  /* #5: @5 = ||@0||_F */
  w05 = casadi_norm_2(4, w00);
  /* #6: @6 = sq(@5) */
  w06 = casadi_sq( w05 );
  /* #7: @4 = (@4/@6) */
  for (i=0, rr=w04; i<4; ++i) (*rr++) /= w06;
  /* #8: @7 = @4[0] */
  for (rr=(&w07), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #9: @3 = @4[1:4] */
  for (rr=w03, cs=w04+1; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #10: @8 = (-@3) */
  for (i=0, rr=w08, cs=w03; i<3; ++i) *rr++ = (- *cs++ );
  /* #11: @9 = vertcat(@7, @8) */
  rr=w09;
  *rr++ = w07;
  for (i=0, cs=w08; i<3; ++i) *rr++ = *cs++;
  /* #12: @10 = ||@4||_F */
  w10 = casadi_norm_2(4, w04);
  /* #13: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #14: @9 = (@9/@11) */
  for (i=0, rr=w09; i<4; ++i) (*rr++) /= w11;
  /* #15: @8 = @9[1:4] */
  for (rr=w08, cs=w09+1; cs!=w09+4; cs+=1) *rr++ = *cs;
  /* #16: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #17: @13 = -0.0949 */
  w13 = -9.4899999999999998e-02;
  /* #18: @14 = @9[0] */
  for (rr=(&w14), cs=w09+0; cs!=w09+1; cs+=1) *rr++ = *cs;
  /* #19: @15 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w15);
  /* #20: @16 = (@7*@15) */
  for (i=0, rr=w16, cs=w15; i<3; ++i) (*rr++)  = (w07*(*cs++));
  /* #21: @17 = @4[2] */
  for (rr=(&w17), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #22: @18 = @15[2] */
  for (rr=(&w18), cs=w15+2; cs!=w15+3; cs+=1) *rr++ = *cs;
  /* #23: @19 = (@17*@18) */
  w19  = (w17*w18);
  /* #24: @20 = @4[3] */
  for (rr=(&w20), cs=w04+3; cs!=w04+4; cs+=1) *rr++ = *cs;
  /* #25: @21 = @15[1] */
  for (rr=(&w21), cs=w15+1; cs!=w15+2; cs+=1) *rr++ = *cs;
  /* #26: @22 = (@20*@21) */
  w22  = (w20*w21);
  /* #27: @19 = (@19-@22) */
  w19 -= w22;
  /* #28: @22 = @15[0] */
  for (rr=(&w22), cs=w15+0; cs!=w15+1; cs+=1) *rr++ = *cs;
  /* #29: @23 = (@20*@22) */
  w23  = (w20*w22);
  /* #30: @24 = @4[1] */
  for (rr=(&w24), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #31: @25 = (@24*@18) */
  w25  = (w24*w18);
  /* #32: @23 = (@23-@25) */
  w23 -= w25;
  /* #33: @25 = (@24*@21) */
  w25  = (w24*w21);
  /* #34: @26 = (@17*@22) */
  w26  = (w17*w22);
  /* #35: @25 = (@25-@26) */
  w25 -= w26;
  /* #36: @27 = vertcat(@19, @23, @25) */
  rr=w27;
  *rr++ = w19;
  *rr++ = w23;
  *rr++ = w25;
  /* #37: @16 = (@16+@27) */
  for (i=0, rr=w16, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #38: @27 = (@14*@16) */
  for (i=0, rr=w27, cs=w16; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #39: @19 = dot(@3, @15) */
  w19 = casadi_dot(3, w03, w15);
  /* #40: @28 = (@19*@8) */
  for (i=0, rr=w28, cs=w08; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #41: @27 = (@27-@28) */
  for (i=0, rr=w27, cs=w28; i<3; ++i) (*rr++) -= (*cs++);
  /* #42: @23 = @16[1] */
  for (rr=(&w23), cs=w16+1; cs!=w16+2; cs+=1) *rr++ = *cs;
  /* #43: @25 = @9[3] */
  for (rr=(&w25), cs=w09+3; cs!=w09+4; cs+=1) *rr++ = *cs;
  /* #44: @26 = (@23*@25) */
  w26  = (w23*w25);
  /* #45: @29 = @16[2] */
  for (rr=(&w29), cs=w16+2; cs!=w16+3; cs+=1) *rr++ = *cs;
  /* #46: @30 = @9[2] */
  for (rr=(&w30), cs=w09+2; cs!=w09+3; cs+=1) *rr++ = *cs;
  /* #47: @31 = (@29*@30) */
  w31  = (w29*w30);
  /* #48: @26 = (@26-@31) */
  w26 -= w31;
  /* #49: @31 = @9[1] */
  for (rr=(&w31), cs=w09+1; cs!=w09+2; cs+=1) *rr++ = *cs;
  /* #50: @32 = (@29*@31) */
  w32  = (w29*w31);
  /* #51: @33 = @16[0] */
  for (rr=(&w33), cs=w16+0; cs!=w16+1; cs+=1) *rr++ = *cs;
  /* #52: @34 = (@33*@25) */
  w34  = (w33*w25);
  /* #53: @32 = (@32-@34) */
  w32 -= w34;
  /* #54: @34 = (@33*@30) */
  w34  = (w33*w30);
  /* #55: @35 = (@23*@31) */
  w35  = (w23*w31);
  /* #56: @34 = (@34-@35) */
  w34 -= w35;
  /* #57: @28 = vertcat(@26, @32, @34) */
  rr=w28;
  *rr++ = w26;
  *rr++ = w32;
  *rr++ = w34;
  /* #58: @27 = (@27+@28) */
  for (i=0, rr=w27, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #59: @26 = @27[2] */
  for (rr=(&w26), cs=w27+2; cs!=w27+3; cs+=1) *rr++ = *cs;
  /* #60: @32 = (@13*@26) */
  w32  = (w13*w26);
  /* #61: @28 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w28);
  /* #62: @36 = input[1][0] */
  wr36 = arg[1] ? arg[1] : casadi_zeros;
  /* #63: {@37, @38, @39, @40, @34, @41} = vertsplit(@36) */
  wr37 = wr36;
  wr38 = wr36+3;
  wr39 = wr36+6;
  wr40 = wr36+10;
  w34 = wr36[13];
  wr41 = wr36+14;
  /* #64: @42 = (-@38) */
  for (i=0, rr=w42, cs=wr38; i<3; ++i) *rr++ = (- *cs++ );
  /* #65: @35 = dot(@3, @42) */
  w35 = casadi_dot(3, w03, w42);
  /* #66: @42 = (@35*@2) */
  for (i=0, rr=w42, cs=w02; i<3; ++i) (*rr++)  = (w35*(*cs++));
  /* #67: @43 = @0[3] */
  for (rr=(&w43), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #68: {@44, @45, @46} = vertsplit(@38) */
  w44 = wr38[0];
  w45 = wr38[1];
  w46 = wr38[2];
  /* #69: @47 = (@17*@46) */
  w47  = (w17*w46);
  /* #70: @48 = (@20*@45) */
  w48  = (w20*w45);
  /* #71: @47 = (@47-@48) */
  w47 -= w48;
  /* #72: @49 = @12; (@49[0] += @47) */
  casadi_copy(w12, 3, w49);
  for (rr=w49+0, cs=(&w47); rr!=w49+1; rr+=1) *rr += *cs++;
  /* #73: @47 = (@24*@45) */
  w47  = (w24*w45);
  /* #74: @48 = (@17*@44) */
  w48  = (w17*w44);
  /* #75: @47 = (@47-@48) */
  w47 -= w48;
  /* #76: (@49[2] += @47) */
  for (rr=w49+2, cs=(&w47); rr!=w49+3; rr+=1) *rr += *cs++;
  /* #77: @47 = (@20*@44) */
  w47  = (w20*w44);
  /* #78: @48 = (@24*@46) */
  w48  = (w24*w46);
  /* #79: @47 = (@47-@48) */
  w47 -= w48;
  /* #80: (@49[1] += @47) */
  for (rr=w49+1, cs=(&w47); rr!=w49+2; rr+=1) *rr += *cs++;
  /* #81: @50 = (@7*@38) */
  for (i=0, rr=w50, cs=wr38; i<3; ++i) (*rr++)  = (w07*(*cs++));
  /* #82: @49 = (@49+@50) */
  for (i=0, rr=w49, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #83: {@47, @48, @51} = vertsplit(@49) */
  w47 = w49[0];
  w48 = w49[1];
  w51 = w49[2];
  /* #84: @52 = (@43*@48) */
  w52  = (w43*w48);
  /* #85: @53 = @0[2] */
  for (rr=(&w53), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #86: @54 = (@53*@51) */
  w54  = (w53*w51);
  /* #87: @52 = (@52-@54) */
  w52 -= w54;
  /* #88: (@42[0] += @52) */
  for (rr=w42+0, cs=(&w52); rr!=w42+1; rr+=1) *rr += *cs++;
  /* #89: @52 = @0[1] */
  for (rr=(&w52), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #90: @54 = (@52*@51) */
  w54  = (w52*w51);
  /* #91: @55 = (@43*@47) */
  w55  = (w43*w47);
  /* #92: @54 = (@54-@55) */
  w54 -= w55;
  /* #93: (@42[1] += @54) */
  for (rr=w42+1, cs=(&w54); rr!=w42+2; rr+=1) *rr += *cs++;
  /* #94: @54 = (@53*@47) */
  w54  = (w53*w47);
  /* #95: @55 = (@52*@48) */
  w55  = (w52*w48);
  /* #96: @54 = (@54-@55) */
  w54 -= w55;
  /* #97: (@42[2] += @54) */
  for (rr=w42+2, cs=(&w54); rr!=w42+3; rr+=1) *rr += *cs++;
  /* #98: @50 = (@1*@49) */
  for (i=0, rr=w50, cs=w49; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #99: @42 = (@42+@50) */
  for (i=0, rr=w42, cs=w50; i<3; ++i) (*rr++) += (*cs++);
  /* #100: @54 = dot(@28, @42) */
  w54 = casadi_dot(3, w28, w42);
  /* #101: @55 = (@32*@54) */
  w55  = (w32*w54);
  /* #102: @50 = @12; (@50[2] += @55) */
  casadi_copy(w12, 3, w50);
  for (rr=w50+2, cs=(&w55); rr!=w50+3; rr+=1) *rr += *cs++;
  /* #103: @55 = (@26*@54) */
  w55  = (w26*w54);
  /* #104: @13 = (@13*@55) */
  w13 *= w55;
  /* #105: (@50[2] += @13) */
  for (rr=w50+2, cs=(&w13); rr!=w50+3; rr+=1) *rr += *cs++;
  /* #106: @13 = @27[1] */
  for (rr=(&w13), cs=w27+1; cs!=w27+2; cs+=1) *rr++ = *cs;
  /* #107: @55 = (2.*@13) */
  w55 = (2.* w13 );
  /* #108: @56 = 0.005 */
  w56 = 5.0000000000000001e-03;
  /* #109: @54 = (@56*@54) */
  w54  = (w56*w54);
  /* #110: @55 = (@55*@54) */
  w55 *= w54;
  /* #111: (@50[1] += @55) */
  for (rr=w50+1, cs=(&w55); rr!=w50+2; rr+=1) *rr += *cs++;
  /* #112: @55 = @27[0] */
  for (rr=(&w55), cs=w27+0; cs!=w27+1; cs+=1) *rr++ = *cs;
  /* #113: @57 = (2.*@55) */
  w57 = (2.* w55 );
  /* #114: @57 = (@57*@54) */
  w57 *= w54;
  /* #115: (@50[0] += @57) */
  for (rr=w50+0, cs=(&w57); rr!=w50+1; rr+=1) *rr += *cs++;
  /* #116: @58 = [-0.2918, -0.3153, -0.0167] */
  casadi_copy(casadi_c1, 3, w58);
  /* #117: @42 = (@58*@42) */
  for (i=0, rr=w42, cr=w58, cs=w42; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #118: @50 = (@50+@42) */
  for (i=0, rr=w50, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #119: @42 = (-@50) */
  for (i=0, rr=w42, cs=w50; i<3; ++i) *rr++ = (- *cs++ );
  /* #120: @57 = dot(@8, @42) */
  w57 = casadi_dot(3, w08, w42);
  /* #121: @8 = (@57*@3) */
  for (i=0, rr=w08, cs=w03; i<3; ++i) (*rr++)  = (w57*(*cs++));
  /* #122: {@54, @59, @60} = vertsplit(@50) */
  w54 = w50[0];
  w59 = w50[1];
  w60 = w50[2];
  /* #123: @61 = (@30*@60) */
  w61  = (w30*w60);
  /* #124: @62 = (@25*@59) */
  w62  = (w25*w59);
  /* #125: @61 = (@61-@62) */
  w61 -= w62;
  /* #126: @42 = @12; (@42[0] += @61) */
  casadi_copy(w12, 3, w42);
  for (rr=w42+0, cs=(&w61); rr!=w42+1; rr+=1) *rr += *cs++;
  /* #127: @61 = (@31*@59) */
  w61  = (w31*w59);
  /* #128: @30 = (@30*@54) */
  w30 *= w54;
  /* #129: @61 = (@61-@30) */
  w61 -= w30;
  /* #130: (@42[2] += @61) */
  for (rr=w42+2, cs=(&w61); rr!=w42+3; rr+=1) *rr += *cs++;
  /* #131: @25 = (@25*@54) */
  w25 *= w54;
  /* #132: @31 = (@31*@60) */
  w31 *= w60;
  /* #133: @25 = (@25-@31) */
  w25 -= w31;
  /* #134: (@42[1] += @25) */
  for (rr=w42+1, cs=(&w25); rr!=w42+2; rr+=1) *rr += *cs++;
  /* #135: @63 = (@14*@50) */
  for (i=0, rr=w63, cs=w50; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #136: @42 = (@42+@63) */
  for (i=0, rr=w42, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #137: {@14, @25, @31} = vertsplit(@42) */
  w14 = w42[0];
  w25 = w42[1];
  w31 = w42[2];
  /* #138: @61 = (@20*@25) */
  w61  = (w20*w25);
  /* #139: @30 = (@17*@31) */
  w30  = (w17*w31);
  /* #140: @61 = (@61-@30) */
  w61 -= w30;
  /* #141: (@8[0] += @61) */
  for (rr=w08+0, cs=(&w61); rr!=w08+1; rr+=1) *rr += *cs++;
  /* #142: @61 = (@24*@31) */
  w61  = (w24*w31);
  /* #143: @30 = (@20*@14) */
  w30  = (w20*w14);
  /* #144: @61 = (@61-@30) */
  w61 -= w30;
  /* #145: (@8[1] += @61) */
  for (rr=w08+1, cs=(&w61); rr!=w08+2; rr+=1) *rr += *cs++;
  /* #146: @61 = (@17*@14) */
  w61  = (w17*w14);
  /* #147: @30 = (@24*@25) */
  w30  = (w24*w25);
  /* #148: @61 = (@61-@30) */
  w61 -= w30;
  /* #149: (@8[2] += @61) */
  for (rr=w08+2, cs=(&w61); rr!=w08+3; rr+=1) *rr += *cs++;
  /* #150: @63 = (@7*@42) */
  for (i=0, rr=w63, cs=w42; i<3; ++i) (*rr++)  = (w07*(*cs++));
  /* #151: @8 = (@8+@63) */
  for (i=0, rr=w08, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #152: @8 = (@8+@37) */
  for (i=0, rr=w08, cs=wr37; i<3; ++i) (*rr++) += (*cs++);
  /* #153: output[0][0] = @8 */
  casadi_copy(w08, 3, res[0]);
  /* #154: @64 = zeros(4x1) */
  casadi_clear(w64, 4);
  /* #155: @8 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w08);
  /* #156: @61 = @8[1] */
  for (rr=(&w61), cs=w08+1; cs!=w08+2; cs+=1) *rr++ = *cs;
  /* #157: @30 = 0.5 */
  w30 = 5.0000000000000000e-01;
  /* #158: @39 = (@30*@39) */
  for (i=0, rr=w39, cs=wr39; i<4; ++i) (*rr++)  = (w30*(*cs++));
  /* #159: {@30, @37} = vertsplit(@39) */
  w30 = w39[0];
  casadi_copy(w39+1, 3, w37);
  /* #160: {@62, @65, @66} = vertsplit(@37) */
  w62 = w37[0];
  w65 = w37[1];
  w66 = w37[2];
  /* #161: @67 = (@61*@66) */
  w67  = (w61*w66);
  /* #162: @68 = @8[2] */
  for (rr=(&w68), cs=w08+2; cs!=w08+3; cs+=1) *rr++ = *cs;
  /* #163: @69 = (@68*@65) */
  w69  = (w68*w65);
  /* #164: @67 = (@67-@69) */
  w67 -= w69;
  /* #165: @39 = @64; (@39[1] += @67) */
  casadi_copy(w64, 4, w39);
  for (rr=w39+1, cs=(&w67); rr!=w39+2; rr+=1) *rr += *cs++;
  /* #166: @67 = @8[0] */
  for (rr=(&w67), cs=w08+0; cs!=w08+1; cs+=1) *rr++ = *cs;
  /* #167: @69 = (@67*@65) */
  w69  = (w67*w65);
  /* #168: @61 = (@61*@62) */
  w61 *= w62;
  /* #169: @69 = (@69-@61) */
  w69 -= w61;
  /* #170: (@39[3] += @69) */
  for (rr=w39+3, cs=(&w69); rr!=w39+4; rr+=1) *rr += *cs++;
  /* #171: @68 = (@68*@62) */
  w68 *= w62;
  /* #172: @67 = (@67*@66) */
  w67 *= w66;
  /* #173: @68 = (@68-@67) */
  w68 -= w67;
  /* #174: (@39[2] += @68) */
  for (rr=w39+2, cs=(&w68); rr!=w39+3; rr+=1) *rr += *cs++;
  /* #175: @68 = dot(@8, @37) */
  w68 = casadi_dot(3, w08, w37);
  /* #176: (@39[0] += @68) */
  for (rr=w39+0, cs=(&w68); rr!=w39+1; rr+=1) *rr += *cs++;
  /* #177: @8 = (@30*@8) */
  for (i=0, rr=w08, cs=w08; i<3; ++i) (*rr++)  = (w30*(*cs++));
  /* #178: @8 = (-@8) */
  for (i=0, rr=w08, cs=w08; i<3; ++i) *rr++ = (- *cs++ );
  /* #179: (@39[1:4] += @8) */
  for (rr=w39+1, cs=w08; rr!=w39+4; rr+=1) *rr += *cs++;
  /* #180: @58 = (@58*@27) */
  for (i=0, rr=w58, cs=w27; i<3; ++i) (*rr++) *= (*cs++);
  /* #181: @55 = sq(@55) */
  w55 = casadi_sq( w55 );
  /* #182: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #183: @55 = (@55+@13) */
  w55 += w13;
  /* #184: @56 = (@56*@55) */
  w56 *= w55;
  /* #185: @32 = (@32*@26) */
  w32 *= w26;
  /* #186: @56 = (@56+@32) */
  w56 += w32;
  /* #187: @27 = (@28*@56) */
  for (i=0, rr=w27, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w56);
  /* #188: @58 = (@58+@27) */
  for (i=0, rr=w58, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #189: @27 = (@35*@58) */
  for (i=0, rr=w27, cs=w58; i<3; ++i) (*rr++)  = (w35*(*cs++));
  /* #190: (@39[1:4] += @27) */
  for (rr=w39+1, cs=w27; rr!=w39+4; rr+=1) *rr += *cs++;
  /* #191: @35 = @58[1] */
  for (rr=(&w35), cs=w58+1; cs!=w58+2; cs+=1) *rr++ = *cs;
  /* #192: @56 = (@35*@51) */
  w56  = (w35*w51);
  /* #193: @32 = @58[2] */
  for (rr=(&w32), cs=w58+2; cs!=w58+3; cs+=1) *rr++ = *cs;
  /* #194: @26 = (@32*@48) */
  w26  = (w32*w48);
  /* #195: @56 = (@56-@26) */
  w56 -= w26;
  /* #196: (@39[1] += @56) */
  for (rr=w39+1, cs=(&w56); rr!=w39+2; rr+=1) *rr += *cs++;
  /* #197: @56 = @58[0] */
  for (rr=(&w56), cs=w58+0; cs!=w58+1; cs+=1) *rr++ = *cs;
  /* #198: @48 = (@56*@48) */
  w48  = (w56*w48);
  /* #199: @26 = (@35*@47) */
  w26  = (w35*w47);
  /* #200: @48 = (@48-@26) */
  w48 -= w26;
  /* #201: (@39[3] += @48) */
  for (rr=w39+3, cs=(&w48); rr!=w39+4; rr+=1) *rr += *cs++;
  /* #202: @47 = (@32*@47) */
  w47  = (w32*w47);
  /* #203: @51 = (@56*@51) */
  w51  = (w56*w51);
  /* #204: @47 = (@47-@51) */
  w47 -= w51;
  /* #205: (@39[2] += @47) */
  for (rr=w39+2, cs=(&w47); rr!=w39+3; rr+=1) *rr += *cs++;
  /* #206: @47 = (2.*@5) */
  w47 = (2.* w05 );
  /* #207: @70 = (@4/@6) */
  for (i=0, rr=w70, cr=w04; i<4; ++i) (*rr++)  = ((*cr++)/w06);
  /* #208: @70 = (-@70) */
  for (i=0, rr=w70, cs=w70; i<4; ++i) *rr++ = (- *cs++ );
  /* #209: @27 = (@57*@15) */
  for (i=0, rr=w27, cs=w15; i<3; ++i) (*rr++)  = (w57*(*cs++));
  /* #210: @71 = @64; (@71[1:4] += @27) */
  casadi_copy(w64, 4, w71);
  for (rr=w71+1, cs=w27; rr!=w71+4; rr+=1) *rr += *cs++;
  /* #211: @57 = (@21*@31) */
  w57  = (w21*w31);
  /* #212: @51 = (@18*@25) */
  w51  = (w18*w25);
  /* #213: @57 = (@57-@51) */
  w57 -= w51;
  /* #214: (@71[1] += @57) */
  for (rr=w71+1, cs=(&w57); rr!=w71+2; rr+=1) *rr += *cs++;
  /* #215: @25 = (@22*@25) */
  w25  = (w22*w25);
  /* #216: @21 = (@21*@14) */
  w21 *= w14;
  /* #217: @25 = (@25-@21) */
  w25 -= w21;
  /* #218: (@71[3] += @25) */
  for (rr=w71+3, cs=(&w25); rr!=w71+4; rr+=1) *rr += *cs++;
  /* #219: @18 = (@18*@14) */
  w18 *= w14;
  /* #220: @22 = (@22*@31) */
  w22 *= w31;
  /* #221: @18 = (@18-@22) */
  w18 -= w22;
  /* #222: (@71[2] += @18) */
  for (rr=w71+2, cs=(&w18); rr!=w71+3; rr+=1) *rr += *cs++;
  /* #223: @18 = dot(@15, @42) */
  w18 = casadi_dot(3, w15, w42);
  /* #224: (@71[0] += @18) */
  for (rr=w71+0, cs=(&w18); rr!=w71+1; rr+=1) *rr += *cs++;
  /* #225: @18 = (2.*@10) */
  w18 = (2.* w10 );
  /* #226: @9 = (@9/@11) */
  for (i=0, rr=w09; i<4; ++i) (*rr++) /= w11;
  /* #227: @9 = (-@9) */
  for (i=0, rr=w09, cs=w09; i<4; ++i) *rr++ = (- *cs++ );
  /* #228: @22 = (@29*@59) */
  w22  = (w29*w59);
  /* #229: @31 = (@23*@60) */
  w31  = (w23*w60);
  /* #230: @22 = (@22-@31) */
  w22 -= w31;
  /* #231: @72 = @64; (@72[1] += @22) */
  casadi_copy(w64, 4, w72);
  for (rr=w72+1, cs=(&w22); rr!=w72+2; rr+=1) *rr += *cs++;
  /* #232: @60 = (@33*@60) */
  w60  = (w33*w60);
  /* #233: @29 = (@29*@54) */
  w29 *= w54;
  /* #234: @60 = (@60-@29) */
  w60 -= w29;
  /* #235: (@72[2] += @60) */
  for (rr=w72+2, cs=(&w60); rr!=w72+3; rr+=1) *rr += *cs++;
  /* #236: @23 = (@23*@54) */
  w23 *= w54;
  /* #237: @33 = (@33*@59) */
  w33 *= w59;
  /* #238: @23 = (@23-@33) */
  w23 -= w33;
  /* #239: (@72[3] += @23) */
  for (rr=w72+3, cs=(&w23); rr!=w72+4; rr+=1) *rr += *cs++;
  /* #240: @15 = (@19*@50) */
  for (i=0, rr=w15, cs=w50; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #241: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) *rr++ = (- *cs++ );
  /* #242: (@72[1:4] += @15) */
  for (rr=w72+1, cs=w15; rr!=w72+4; rr+=1) *rr += *cs++;
  /* #243: @19 = dot(@16, @50) */
  w19 = casadi_dot(3, w16, w50);
  /* #244: (@72[0] += @19) */
  for (rr=w72+0, cs=(&w19); rr!=w72+1; rr+=1) *rr += *cs++;
  /* #245: @19 = dot(@9, @72) */
  w19 = casadi_dot(4, w09, w72);
  /* #246: @18 = (@18*@19) */
  w18 *= w19;
  /* #247: @18 = (@18/@10) */
  w18 /= w10;
  /* #248: @4 = (@18*@4) */
  for (i=0, rr=w04, cs=w04; i<4; ++i) (*rr++)  = (w18*(*cs++));
  /* #249: @71 = (@71+@4) */
  for (i=0, rr=w71, cs=w04; i<4; ++i) (*rr++) += (*cs++);
  /* #250: @72 = (@72/@11) */
  for (i=0, rr=w72; i<4; ++i) (*rr++) /= w11;
  /* #251: {@11, @16} = vertsplit(@72) */
  w11 = w72[0];
  casadi_copy(w72+1, 3, w16);
  /* #252: @16 = (-@16) */
  for (i=0, rr=w16, cs=w16; i<3; ++i) *rr++ = (- *cs++ );
  /* #253: (@71[1:4] += @16) */
  for (rr=w71+1, cs=w16; rr!=w71+4; rr+=1) *rr += *cs++;
  /* #254: (@71[0] += @11) */
  for (rr=w71+0, cs=(&w11); rr!=w71+1; rr+=1) *rr += *cs++;
  /* #255: @11 = dot(@70, @71) */
  w11 = casadi_dot(4, w70, w71);
  /* #256: @11 = (@47*@11) */
  w11  = (w47*w11);
  /* #257: @11 = (@11/@5) */
  w11 /= w05;
  /* #258: @72 = (@11*@0) */
  for (i=0, rr=w72, cs=w00; i<4; ++i) (*rr++)  = (w11*(*cs++));
  /* #259: @39 = (@39+@72) */
  for (i=0, rr=w39, cs=w72; i<4; ++i) (*rr++) += (*cs++);
  /* #260: @71 = (@71/@6) */
  for (i=0, rr=w71; i<4; ++i) (*rr++) /= w06;
  /* #261: {@11, @16} = vertsplit(@71) */
  w11 = w71[0];
  casadi_copy(w71+1, 3, w16);
  /* #262: @16 = (-@16) */
  for (i=0, rr=w16, cs=w16; i<3; ++i) *rr++ = (- *cs++ );
  /* #263: (@39[1:4] += @16) */
  for (rr=w39+1, cs=w16; rr!=w39+4; rr+=1) *rr += *cs++;
  /* #264: (@39[0] += @11) */
  for (rr=w39+0, cs=(&w11); rr!=w39+1; rr+=1) *rr += *cs++;
  /* #265: @11 = dot(@58, @49) */
  w11 = casadi_dot(3, w58, w49);
  /* #266: (@39[0] += @11) */
  for (rr=w39+0, cs=(&w11); rr!=w39+1; rr+=1) *rr += *cs++;
  /* #267: @49 = (@1*@58) */
  for (i=0, rr=w49, cs=w58; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #268: @11 = (@53*@32) */
  w11  = (w53*w32);
  /* #269: @18 = (@43*@35) */
  w18  = (w43*w35);
  /* #270: @11 = (@11-@18) */
  w11 -= w18;
  /* #271: @18 = (@43*@56) */
  w18  = (w43*w56);
  /* #272: @32 = (@52*@32) */
  w32  = (w52*w32);
  /* #273: @18 = (@18-@32) */
  w18 -= w32;
  /* #274: @35 = (@52*@35) */
  w35  = (w52*w35);
  /* #275: @56 = (@53*@56) */
  w56  = (w53*w56);
  /* #276: @35 = (@35-@56) */
  w35 -= w56;
  /* #277: @16 = vertcat(@11, @18, @35) */
  rr=w16;
  *rr++ = w11;
  *rr++ = w18;
  *rr++ = w35;
  /* #278: @49 = (@49+@16) */
  for (i=0, rr=w49, cs=w16; i<3; ++i) (*rr++) += (*cs++);
  /* #279: @11 = @49[2] */
  for (rr=(&w11), cs=w49+2; cs!=w49+3; cs+=1) *rr++ = *cs;
  /* #280: @18 = (@11*@45) */
  w18  = (w11*w45);
  /* #281: @35 = @49[1] */
  for (rr=(&w35), cs=w49+1; cs!=w49+2; cs+=1) *rr++ = *cs;
  /* #282: @56 = (@35*@46) */
  w56  = (w35*w46);
  /* #283: @18 = (@18-@56) */
  w18 -= w56;
  /* #284: @71 = @64; (@71[1] += @18) */
  casadi_copy(w64, 4, w71);
  for (rr=w71+1, cs=(&w18); rr!=w71+2; rr+=1) *rr += *cs++;
  /* #285: @18 = @49[0] */
  for (rr=(&w18), cs=w49+0; cs!=w49+1; cs+=1) *rr++ = *cs;
  /* #286: @46 = (@18*@46) */
  w46  = (w18*w46);
  /* #287: @11 = (@11*@44) */
  w11 *= w44;
  /* #288: @46 = (@46-@11) */
  w46 -= w11;
  /* #289: (@71[2] += @46) */
  for (rr=w71+2, cs=(&w46); rr!=w71+3; rr+=1) *rr += *cs++;
  /* #290: @35 = (@35*@44) */
  w35 *= w44;
  /* #291: @18 = (@18*@45) */
  w18 *= w45;
  /* #292: @35 = (@35-@18) */
  w35 -= w18;
  /* #293: (@71[3] += @35) */
  for (rr=w71+3, cs=(&w35); rr!=w71+4; rr+=1) *rr += *cs++;
  /* #294: @35 = dot(@2, @58) */
  w35 = casadi_dot(3, w02, w58);
  /* #295: @58 = (@35*@38) */
  for (i=0, rr=w58, cs=wr38; i<3; ++i) (*rr++)  = (w35*(*cs++));
  /* #296: @58 = (-@58) */
  for (i=0, rr=w58, cs=w58; i<3; ++i) *rr++ = (- *cs++ );
  /* #297: (@71[1:4] += @58) */
  for (rr=w71+1, cs=w58; rr!=w71+4; rr+=1) *rr += *cs++;
  /* #298: @35 = dot(@49, @38) */
  w35 = casadi_dot(3, w49, wr38);
  /* #299: (@71[0] += @35) */
  for (rr=w71+0, cs=(&w35); rr!=w71+1; rr+=1) *rr += *cs++;
  /* #300: @35 = dot(@70, @71) */
  w35 = casadi_dot(4, w70, w71);
  /* #301: @35 = (@47*@35) */
  w35  = (w47*w35);
  /* #302: @35 = (@35/@5) */
  w35 /= w05;
  /* #303: @72 = (@35*@0) */
  for (i=0, rr=w72, cs=w00; i<4; ++i) (*rr++)  = (w35*(*cs++));
  /* #304: @39 = (@39+@72) */
  for (i=0, rr=w39, cs=w72; i<4; ++i) (*rr++) += (*cs++);
  /* #305: @71 = (@71/@6) */
  for (i=0, rr=w71; i<4; ++i) (*rr++) /= w06;
  /* #306: {@35, @49} = vertsplit(@71) */
  w35 = w71[0];
  casadi_copy(w71+1, 3, w49);
  /* #307: @49 = (-@49) */
  for (i=0, rr=w49, cs=w49; i<3; ++i) *rr++ = (- *cs++ );
  /* #308: (@39[1:4] += @49) */
  for (rr=w39+1, cs=w49; rr!=w39+4; rr+=1) *rr += *cs++;
  /* #309: (@39[0] += @35) */
  for (rr=w39+0, cs=(&w35); rr!=w39+1; rr+=1) *rr += *cs++;
  /* #310: @35 = input[0][4] */
  w35 = arg[0] ? arg[0][13] : 0;
  /* #311: @49 = (@35*@38) */
  for (i=0, rr=w49, cs=wr38; i<3; ++i) (*rr++)  = (w35*(*cs++));
  /* #312: @58 = (-@49) */
  for (i=0, rr=w58, cs=w49; i<3; ++i) *rr++ = (- *cs++ );
  /* #313: @35 = dot(@3, @58) */
  w35 = casadi_dot(3, w03, w58);
  /* #314: @58 = (@28*@35) */
  for (i=0, rr=w58, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w35);
  /* #315: (@39[1:4] += @58) */
  for (rr=w39+1, cs=w58; rr!=w39+4; rr+=1) *rr += *cs++;
  /* #316: @35 = @28[1] */
  for (rr=(&w35), cs=w28+1; cs!=w28+2; cs+=1) *rr++ = *cs;
  /* #317: {@18, @45, @44} = vertsplit(@49) */
  w18 = w49[0];
  w45 = w49[1];
  w44 = w49[2];
  /* #318: @46 = (@17*@44) */
  w46  = (w17*w44);
  /* #319: @11 = (@20*@45) */
  w11  = (w20*w45);
  /* #320: @46 = (@46-@11) */
  w46 -= w11;
  /* #321: (@12[0] += @46) */
  for (rr=w12+0, cs=(&w46); rr!=w12+1; rr+=1) *rr += *cs++;
  /* #322: @46 = (@24*@45) */
  w46  = (w24*w45);
  /* #323: @11 = (@17*@18) */
  w11  = (w17*w18);
  /* #324: @46 = (@46-@11) */
  w46 -= w11;
  /* #325: (@12[2] += @46) */
  for (rr=w12+2, cs=(&w46); rr!=w12+3; rr+=1) *rr += *cs++;
  /* #326: @46 = (@20*@18) */
  w46  = (w20*w18);
  /* #327: @11 = (@24*@44) */
  w11  = (w24*w44);
  /* #328: @46 = (@46-@11) */
  w46 -= w11;
  /* #329: (@12[1] += @46) */
  for (rr=w12+1, cs=(&w46); rr!=w12+2; rr+=1) *rr += *cs++;
  /* #330: @58 = (@7*@49) */
  for (i=0, rr=w58, cs=w49; i<3; ++i) (*rr++)  = (w07*(*cs++));
  /* #331: @12 = (@12+@58) */
  for (i=0, rr=w12, cs=w58; i<3; ++i) (*rr++) += (*cs++);
  /* #332: {@46, @11, @56} = vertsplit(@12) */
  w46 = w12[0];
  w11 = w12[1];
  w56 = w12[2];
  /* #333: @32 = (@35*@56) */
  w32  = (w35*w56);
  /* #334: @10 = @28[2] */
  for (rr=(&w10), cs=w28+2; cs!=w28+3; cs+=1) *rr++ = *cs;
  /* #335: @19 = (@10*@11) */
  w19  = (w10*w11);
  /* #336: @32 = (@32-@19) */
  w32 -= w19;
  /* #337: (@39[1] += @32) */
  for (rr=w39+1, cs=(&w32); rr!=w39+2; rr+=1) *rr += *cs++;
  /* #338: @32 = @28[0] */
  for (rr=(&w32), cs=w28+0; cs!=w28+1; cs+=1) *rr++ = *cs;
  /* #339: @11 = (@32*@11) */
  w11  = (w32*w11);
  /* #340: @19 = (@35*@46) */
  w19  = (w35*w46);
  /* #341: @11 = (@11-@19) */
  w11 -= w19;
  /* #342: (@39[3] += @11) */
  for (rr=w39+3, cs=(&w11); rr!=w39+4; rr+=1) *rr += *cs++;
  /* #343: @46 = (@10*@46) */
  w46  = (w10*w46);
  /* #344: @56 = (@32*@56) */
  w56  = (w32*w56);
  /* #345: @46 = (@46-@56) */
  w46 -= w56;
  /* #346: (@39[2] += @46) */
  for (rr=w39+2, cs=(&w46); rr!=w39+3; rr+=1) *rr += *cs++;
  /* #347: @46 = dot(@28, @12) */
  w46 = casadi_dot(3, w28, w12);
  /* #348: (@39[0] += @46) */
  for (rr=w39+0, cs=(&w46); rr!=w39+1; rr+=1) *rr += *cs++;
  /* #349: @12 = (@28*@1) */
  for (i=0, rr=w12, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w01);
  /* #350: @46 = (@53*@10) */
  w46  = (w53*w10);
  /* #351: @56 = (@43*@35) */
  w56  = (w43*w35);
  /* #352: @46 = (@46-@56) */
  w46 -= w56;
  /* #353: @56 = (@43*@32) */
  w56  = (w43*w32);
  /* #354: @10 = (@52*@10) */
  w10  = (w52*w10);
  /* #355: @56 = (@56-@10) */
  w56 -= w10;
  /* #356: @35 = (@52*@35) */
  w35  = (w52*w35);
  /* #357: @32 = (@53*@32) */
  w32  = (w53*w32);
  /* #358: @35 = (@35-@32) */
  w35 -= w32;
  /* #359: @58 = vertcat(@46, @56, @35) */
  rr=w58;
  *rr++ = w46;
  *rr++ = w56;
  *rr++ = w35;
  /* #360: @12 = (@12+@58) */
  for (i=0, rr=w12, cs=w58; i<3; ++i) (*rr++) += (*cs++);
  /* #361: @46 = @12[2] */
  for (rr=(&w46), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #362: @56 = (@46*@45) */
  w56  = (w46*w45);
  /* #363: @35 = @12[1] */
  for (rr=(&w35), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #364: @32 = (@35*@44) */
  w32  = (w35*w44);
  /* #365: @56 = (@56-@32) */
  w56 -= w32;
  /* #366: (@64[1] += @56) */
  for (rr=w64+1, cs=(&w56); rr!=w64+2; rr+=1) *rr += *cs++;
  /* #367: @56 = @12[0] */
  for (rr=(&w56), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #368: @44 = (@56*@44) */
  w44  = (w56*w44);
  /* #369: @32 = (@46*@18) */
  w32  = (w46*w18);
  /* #370: @44 = (@44-@32) */
  w44 -= w32;
  /* #371: (@64[2] += @44) */
  for (rr=w64+2, cs=(&w44); rr!=w64+3; rr+=1) *rr += *cs++;
  /* #372: @18 = (@35*@18) */
  w18  = (w35*w18);
  /* #373: @45 = (@56*@45) */
  w45  = (w56*w45);
  /* #374: @18 = (@18-@45) */
  w18 -= w45;
  /* #375: (@64[3] += @18) */
  for (rr=w64+3, cs=(&w18); rr!=w64+4; rr+=1) *rr += *cs++;
  /* #376: @18 = dot(@2, @28) */
  w18 = casadi_dot(3, w02, w28);
  /* #377: @28 = (@18*@49) */
  for (i=0, rr=w28, cs=w49; i<3; ++i) (*rr++)  = (w18*(*cs++));
  /* #378: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) *rr++ = (- *cs++ );
  /* #379: (@64[1:4] += @28) */
  for (rr=w64+1, cs=w28; rr!=w64+4; rr+=1) *rr += *cs++;
  /* #380: @45 = dot(@12, @49) */
  w45 = casadi_dot(3, w12, w49);
  /* #381: (@64[0] += @45) */
  for (rr=w64+0, cs=(&w45); rr!=w64+1; rr+=1) *rr += *cs++;
  /* #382: @45 = dot(@70, @64) */
  w45 = casadi_dot(4, w70, w64);
  /* #383: @47 = (@47*@45) */
  w47 *= w45;
  /* #384: @47 = (@47/@5) */
  w47 /= w05;
  /* #385: @0 = (@47*@0) */
  for (i=0, rr=w00, cs=w00; i<4; ++i) (*rr++)  = (w47*(*cs++));
  /* #386: @39 = (@39+@0) */
  for (i=0, rr=w39, cs=w00; i<4; ++i) (*rr++) += (*cs++);
  /* #387: @64 = (@64/@6) */
  for (i=0, rr=w64; i<4; ++i) (*rr++) /= w06;
  /* #388: {@6, @49} = vertsplit(@64) */
  w06 = w64[0];
  casadi_copy(w64+1, 3, w49);
  /* #389: @49 = (-@49) */
  for (i=0, rr=w49, cs=w49; i<3; ++i) *rr++ = (- *cs++ );
  /* #390: (@39[1:4] += @49) */
  for (rr=w39+1, cs=w49; rr!=w39+4; rr+=1) *rr += *cs++;
  /* #391: (@39[0] += @6) */
  for (rr=w39+0, cs=(&w06); rr!=w39+1; rr+=1) *rr += *cs++;
  /* #392: output[0][1] = @39 */
  if (res[0]) casadi_copy(w39, 4, res[0]+3);
  /* #393: @6 = 20 */
  w06 = 20.;
  /* #394: @40 = (@6*@40) */
  for (i=0, rr=w40, cs=wr40; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #395: @49 = (-@40) */
  for (i=0, rr=w49, cs=w40; i<3; ++i) *rr++ = (- *cs++ );
  /* #396: @6 = (@43*@65) */
  w06  = (w43*w65);
  /* #397: @47 = (@53*@66) */
  w47  = (w53*w66);
  /* #398: @6 = (@6-@47) */
  w06 -= w47;
  /* #399: (@49[0] += @6) */
  for (rr=w49+0, cs=(&w06); rr!=w49+1; rr+=1) *rr += *cs++;
  /* #400: @66 = (@52*@66) */
  w66  = (w52*w66);
  /* #401: @43 = (@43*@62) */
  w43 *= w62;
  /* #402: @66 = (@66-@43) */
  w66 -= w43;
  /* #403: (@49[1] += @66) */
  for (rr=w49+1, cs=(&w66); rr!=w49+2; rr+=1) *rr += *cs++;
  /* #404: @53 = (@53*@62) */
  w53 *= w62;
  /* #405: @52 = (@52*@65) */
  w52 *= w65;
  /* #406: @53 = (@53-@52) */
  w53 -= w52;
  /* #407: (@49[2] += @53) */
  for (rr=w49+2, cs=(&w53); rr!=w49+3; rr+=1) *rr += *cs++;
  /* #408: @37 = (@1*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w01*(*cs++));
  /* #409: @49 = (@49+@37) */
  for (i=0, rr=w49, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #410: @2 = (@30*@2) */
  for (i=0, rr=w02, cs=w02; i<3; ++i) (*rr++)  = (w30*(*cs++));
  /* #411: @49 = (@49-@2) */
  for (i=0, rr=w49, cs=w02; i<3; ++i) (*rr++) -= (*cs++);
  /* #412: output[0][2] = @49 */
  if (res[0]) casadi_copy(w49, 3, res[0]+7);
  /* #413: @12 = (@7*@12) */
  for (i=0, rr=w12, cs=w12; i<3; ++i) (*rr++)  = (w07*(*cs++));
  /* #414: @3 = (@18*@3) */
  for (i=0, rr=w03, cs=w03; i<3; ++i) (*rr++)  = (w18*(*cs++));
  /* #415: @12 = (@12-@3) */
  for (i=0, rr=w12, cs=w03; i<3; ++i) (*rr++) -= (*cs++);
  /* #416: @18 = (@35*@20) */
  w18  = (w35*w20);
  /* #417: @7 = (@46*@17) */
  w07  = (w46*w17);
  /* #418: @18 = (@18-@7) */
  w18 -= w07;
  /* #419: @46 = (@46*@24) */
  w46 *= w24;
  /* #420: @20 = (@56*@20) */
  w20  = (w56*w20);
  /* #421: @46 = (@46-@20) */
  w46 -= w20;
  /* #422: @56 = (@56*@17) */
  w56 *= w17;
  /* #423: @35 = (@35*@24) */
  w35 *= w24;
  /* #424: @56 = (@56-@35) */
  w56 -= w35;
  /* #425: @3 = vertcat(@18, @46, @56) */
  rr=w03;
  *rr++ = w18;
  *rr++ = w46;
  *rr++ = w56;
  /* #426: @12 = (@12+@3) */
  for (i=0, rr=w12, cs=w03; i<3; ++i) (*rr++) += (*cs++);
  /* #427: @18 = dot(@12, @38) */
  w18 = casadi_dot(3, w12, wr38);
  /* #428: output[0][3] = @18 */
  if (res[0]) res[0][10] = w18;
  /* #429: output[0][4] = @40 */
  if (res[0]) casadi_copy(w40, 3, res[0]+11);
  /* #430: output[0][5] = @34 */
  if (res[0]) res[0][14] = w34;
  /* #431: output[0][6] = @41 */
  if (res[0]) casadi_copy(wr41, 3, res[0]+15);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_delay_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_delay_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_delay_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_delay_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_delay_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_delay_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_delay_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_simple_drag_delay_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_delay_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int drone_simple_drag_delay_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real drone_simple_drag_delay_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_delay_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_simple_drag_delay_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_delay_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_simple_drag_delay_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_delay_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 147;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_simple_drag_delay_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 147*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
