# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from flow_publisher/FlowDataMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FlowDataMsg(genpy.Message):
  _md5sum = "66f15ac7ac0281db583d79d134e42e32"
  _type = "flow_publisher/FlowDataMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 flow_x_integral
int16 flow_y_integral
float32 ground_distance
"""
  __slots__ = ['flow_x_integral','flow_y_integral','ground_distance']
  _slot_types = ['int16','int16','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       flow_x_integral,flow_y_integral,ground_distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FlowDataMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.flow_x_integral is None:
        self.flow_x_integral = 0
      if self.flow_y_integral is None:
        self.flow_y_integral = 0
      if self.ground_distance is None:
        self.ground_distance = 0.
    else:
      self.flow_x_integral = 0
      self.flow_y_integral = 0
      self.ground_distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2hf().pack(_x.flow_x_integral, _x.flow_y_integral, _x.ground_distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.flow_x_integral, _x.flow_y_integral, _x.ground_distance,) = _get_struct_2hf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2hf().pack(_x.flow_x_integral, _x.flow_y_integral, _x.ground_distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.flow_x_integral, _x.flow_y_integral, _x.ground_distance,) = _get_struct_2hf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2hf = None
def _get_struct_2hf():
    global _struct_2hf
    if _struct_2hf is None:
        _struct_2hf = struct.Struct("<2hf")
    return _struct_2hf
